[package]
name = "poc"
version = "0.1.0"
authors = ["Michele Orrù <michele.orru@ens.fr>"]
edition = "2018"
keywords = ["cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure="0.1.5"
failure_derive="0.1.5"
merlin = "1.2.0"
rand = "0.7.3"
rand_core = "0.5.1"
rand_chacha = "0.1"
zkp="0.7.0"
sha2="0.8.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"


[dev-dependencies]
criterion = "0.3"

[dependencies.curve25519-dalek]
version = "2.0.0"
features = ["serde", "alloc"]

[[bench]]
name = "pp_benchmarks"
harness = false

[[bench]]
name = "nizk_benchmarks"
harness = false